name: api_client
description: Client to make network calls
version: 0.1.0+1
publish_to: none

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  dio: ^5.2.1+1

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^5.0.0+1
