name: fluttercon
description: Fluttercon Berlin 2023
publish_to: 'none'

version: 1.1.0+5

environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: ^3.10.5

dependencies:
  api_client:
    path: packages/api_client
  cached_network_image: ^3.2.3
  collection: ^1.17.1
  conference_data:
    path: packages/conference_data
  cupertino_icons: ^1.0.2
  dotted_border: ^2.0.0+3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_native_splash: ^2.3.1
  flutter_svg: ^2.0.7
  font_awesome_flutter: ^10.4.0
  get_it: ^7.6.0
  google_fonts: ^4.0.4
  intl: ^0.18.1
  shared_preferences: ^2.1.2
  url_launcher: ^6.1.11
  util:
    path: packages/util

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.0.0+1

flutter:
  uses-material-design: true

  assets:
    - assets/images/